name: Download repos
description: Bulk-download repos as .zip
branding:
  icon: download
  color: blue

inputs:
  ref:
    description: Ref ({refs/heads/<BRANCH> | refs/tags/<TAG> | <SHA>})
    required: true
    default: refs/branch/main
  repos:
    description: Space delimited repos list (<OWNER>/<REPO> [<OWNER>/<REPO> [...]])
    required: true
  output-dir:
    description: Output directory for downloaded repo ({<ABSOLUTE_PATH> | <RELATIVE_PATH>})
    required: true
  access-token:
    description: Github Personal Access Token for accessing repos
    required: true

runs:
  using: "composite"
  steps:
  - name: Set up Python 3.8
    uses: actions/setup-python@v2
    with:
      python-version: 3.8

  - name: Download repos
    run: python ${{ github.action_path }}/download-repos.py --ref ${{ inputs.ref }} --output ${{ inputs.output-dir }} --repos ${{ inputs.repos }}
    shell: bash
    env:
      DOWNLOAD_REPOS_GITHUB_TOKEN: ${{ inputs.access-token }}

  - run: echo "Downloaded the following repos :" && ls -lha ${{ inputs.output-dir }}
    shell: bash
