name: Download repos
description: Download multiple repos (.zip)

inputs:
  ref:
    description: Ref (refs/heads/BRANCH, refs/tags/TAG, SHA)
    required: true
    default: refs/branch/main
  repos:
    description: Comma delimited repo list (OWNER/REPO)
    required: true
  output-dir:
    description: Output directory for downloaded repo
    required: true
  access-token:
    description: Github Personal Access Token for accessing repos
    required: true

runs:
  using: "composite"
  steps:
  - name: Set up Python 3.8
    uses: actions/setup-python@v2
    with:
      python-version: 3.8

  - name: Clone repositories
    run: python ${{ github.action_path }}/clone-repos.py --ref ${{ inputs.ref }} --output ${{ inputs.output-dir }} --repos ${{ inputs.repos }}
    shell: bash
    env:
      CLONE_REPOS_GITHUB_TOKEN: ${{ inputs.access-token }}

  - run: echo "Downloaded the following repos :" && ls -lha ${{ inputs.output-dir }}
    shell: bash
