name: Clone repos

on:
  workflow_call:
    inputs:
      branch:
        type: string
        description: Ref (refs/heads/BRANCH, refs/tags/TAG, SHA)
        required: true
        default: refs/branch/main
      repos:
        type: string
        description: Comma delimited repo list (OWNER/REPO)
        required: true
        default: refs/branch/main
    secrets:
      PAT:
        required: true

jobs:
  execute:
    runs-on: ubuntu-latest

    env:
      CLONE_REPOS_GITHUB_TOKEN: ${{ secrets.PAT }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Clone repositories
        run: python clone-repos.py --ref ${{ github.event.inputs.branch }} --repos ${{ github.event.inputs.repos }} --output repos

      - run: ls -lha repos

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: repos
          path: repos
