name: Clone repos

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Ref to clone (refs/heads/BRANCH, refs/tags/TAG or SHA)
        required: true
        default: refs/heads/main

jobs:
  execute:
    runs-on: ubuntu-latest

    env:
      CLONE_REPOS_GITHUB_TOKEN: ${{ secrets.glo2003_clone_repos }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Clone repositories
        run: python clone-repos.py --ref ${{ github.event.inputs.ref }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: projects
          path: |
            **.zip
          # path: projects
