name: Download projects

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag
        required: true

jobs:
  execute:

    runs-on: ubuntu-latest

    env:
      TAG: ${{ github.event.inputs.tag }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Clone repositories
      run: python clone-repos.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: projects
        path: |
          **.zip
